# Archetype ETL. Generated by mkdag 2025-02-02T21:22:15.137498
# A simple DAG using task decorators

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.datasets import Dataset

from hooks.simple_gene_processing_hook import Check, Extract, Transform, Validate, Load


# load the config
config = json.loads(
    Variable.get("simple_gene_processing", default_var=None)
)  # fmt: off


# Define the Dataset
dataset = Dataset("simple_gene_processing")
scheduled_datasets = [
    Dataset(_) for _ in config["dag"]["extra"].get("scheduled_datasets", [])
]


@dag(
    catchup=False,
    dag_id="simple_gene_processing",
    default_args={"retries": 3, "retry_delay": 5},
    description="A simple DAG using task decorators",
    schedule_interval="@daily",
    start_date=parse("2025-01-01"),
)
def simple_gene_processing_dag():
    """A simple DAG using task decorators"""

    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check() -> Any:
        """Check simple_gene_processing endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task
    def extract(check_result: Any) -> Any:
        """Extract the simple_gene_processing data to S3"""
        return Extract(config, check_result).run()

    @task
    def transform(extract_result: Any) -> Any:
        """Transform the simple_gene_processing data, store results in S3"""
        return Transform(config, extract_result).run()

    @task(outlets=[dataset])
    def validate(transform_result: Any) -> Any:
        """QA the simple_gene_processing Transformation, validate the data, return the transformed data. Update output `dataset`"""
        return Validate(config, transform_result).run()

    @task
    def load(transformed_result: Any) -> bool:
        """Load the Transformed simple_gene_processing data to the destination"""
        status = Load(config, transformed_result).run()
        return status

    # set up the task dependencies
    load(validate(transform(extract(check()))))


# instantiate the DAG
simple_gene_processing_dag()
logging.info("simple_gene_processing DAG instantiated")
