# config_test.yaml
defaults:
  bucket: "fhir-aggregator-public"
  expected_files:
    - ResearchStudy.ndjson
    - ResearchSubject.ndjson
    - Patient.ndjson
    - DocumentReference.ndjson

projects:
  - id: 1KG-Phase1Thru3
  - id: GTEX-V10
  - id: IG
  - id: TCGA-BRCA
  - id: TCGA-HNSC
  - id: TCGA-KIRC
  - id: TCGA-LUAD
  - id: TCGA-LUSC

# for loading data into FHIR store
# this should be filled in by Config.py w/ intelligent defaults
fhir:
  project_id: "test-project-id"
  location_id: "us-central1"
  fhir_store_id: "test-fhir-store-id"
