# Archetype ETL. Generated by mkdag 2025-02-02T20:16:59.582422
# A star wars API DAG

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.datasets import Dataset

from hooks.stapi_hook import Check, Extract, Transform, Validate, Load


# load the config
config = json.loads(Variable.get("stapi", default_var=None))  # fmt: off


# Define the Dataset
dataset = Dataset("stapi")
scheduled_datasets = [
    Dataset(_) for _ in config["dag"]["extra"].get("scheduled_datasets", [])
]


@dag(
    dag_id="stapi",
    default_args={"retries": 3, "retry_delay": 5},
    description="A star wars API DAG",
    start_date=parse("2025-01-01"),
    catchup=False,
    schedule=scheduled_datasets,
)
def stapi_dag():
    """A star wars API DAG"""

    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check() -> Any:
        """Check stapi endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task
    def extract(check_result: Any) -> Any:
        """Extract the stapi data to S3"""
        return Extract(config, check_result).run()

    @task
    def transform(extract_result: Any) -> Any:
        """Transform the stapi data, store results in S3"""
        return Transform(config, extract_result).run()

    @task(outlets=[dataset])
    def validate(transform_result: Any) -> Any:
        """QA the stapi Transformation, validate the data, return the transformed data. Update output `dataset`"""
        return Validate(config, transform_result).run()

    @task
    def load(transformed_result: Any) -> bool:
        """Load the Transformed stapi data to the destination"""
        status = Load(config, transformed_result).run()
        return status

    # set up the task dependencies
    load(validate(transform(extract(check()))))


# instantiate the DAG
stapi_dag()
logging.info("stapi DAG instantiated")
