# Archetype ETL. Generated by mkdag 2025-02-02T10:40:12.161901
# A star wars API DAG

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.datasets import Dataset
from airflow.datasets.metadata import Metadata

from hooks.swapi_hook2 import Config, Check, Extract, Transform, Validate, Load

dag_id = "swapi3"
dag_description = "A star wars API DAG"

# load the config from the Airflow Variable
config_dict = json.loads(Variable.get(dag_id, default_var=None))
if not config_dict:
    raise ValueError(f"No configuration found for {dag_id}")
config = Config(**config_dict)

# Define the Datasets
inlet_datasets = {_: Dataset(_) for _ in config.inlet_datasets}
outlet_datasets = {_: Dataset(_) for _ in config.outlet_datasets or [f"{dag_id}_raw", f"{dag_id}_processed"]}

dag_arguments = {
    "default_args": {"retries": 1, "retry_delay": 5},
    "description": dag_description,
    "start_date": parse("2025-01-01"),
    "catchup": False,
}
if inlet_datasets:
    dag_arguments["schedule"] = inlet_datasets
else:
    dag_arguments["schedule_interval"] = "@daily"

extracted_dataset = next(iter([v for k, v in outlet_datasets.items() if k.endswith("_raw")]))
validated_dataset = next(iter([v for k, v in outlet_datasets.items() if k.endswith("_processed")]))

dag_arguments["dag_id"] = f"{dag_id}_extract"


@dag(**dag_arguments)
def swapi_extract():
    """A star wars API DAG"""

    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check(*args, **kwargs) -> Any:
        """Check swapi endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task(outlets=[extracted_dataset])
    def extract(check_result: Any) -> Any:
        """Extract the swapi data to S3"""
        results = Extract(config).run(check_result)
        yield Metadata(extracted_dataset, {'manifest': results})
        return results

    extract(check())


del dag_arguments["schedule_interval"]
dag_arguments["schedule"] = [extracted_dataset]
dag_arguments["dag_id"] = f"{dag_id}_transform"


@dag(**dag_arguments)
def swapi_transform():

    @task(inlets=[extracted_dataset])
    def transform(inlet_events, *args, **kwargs) -> Any:
        """Transform the swapi data, store results in S3"""
        events = inlet_events[extracted_dataset]
        last_event = events[-1]
        assert last_event, f"No events found for {validated_dataset}"
        assert 'manifest' in last_event.extra, f"No manifest found in {last_event}"
        manifest = last_event.extra['manifest']

        return Transform(config).run(manifest)

    @task(outlets=[validated_dataset])
    def validate(transform_result: Any) -> Any:
        """QA the swapi Transformation, validate the data, return the transformed data"""
        results = Validate(config).run(transform_result)
        yield Metadata(validated_dataset, {'manifest': results})
        return results

    validate(transform())


dag_arguments["schedule"] = [validated_dataset]
dag_arguments["dag_id"] = f"{dag_id}_load"


@dag(**dag_arguments)
def swapi_load():

    @task(inlets=[validated_dataset])
    def load(inlet_events, *args, **kwargs) -> bool:
        """Load the Transformed swapi data to the destination"""
        events = inlet_events[validated_dataset]
        last_event = events[-1]
        assert last_event, f"No events found for {validated_dataset}"
        assert 'manifest' in last_event.extra, f"No manifest found in {last_event}"
        manifest = last_event.extra['manifest']
        status = Load(config).run(manifest)
        return status

    # set up the task dependencies
    load()


# instantiate the DAG
swapi_extract()
swapi_transform()
swapi_load()
logging.info("swapi DAGs instantiated")
