# Archetype ETL. Generated by mkdag 2025-02-02T10:40:12.161901
# A star wars API DAG

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable


from hooks.swapi_hook import Check, Extract, Transform, Validate, Load


@dag(
    catchup=False,
    dag_id="swapi",
    default_args={"retries": 3, "retry_delay": 5},
    description="A star wars API DAG",
    schedule_interval="@daily",
    start_date=parse("2025-01-01"),
)
def swapi_dag():
    """A star wars API DAG"""
    config = json.loads(Variable.get("swapi", default_var=None))  # fmt: off

    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check() -> Any:
        """Check swapi endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task
    def extract(check_result: Any) -> Any:
        """Extract the swapi data to S3"""
        return Extract(config, check_result).run()

    @task
    def transform(extract_result: Any) -> Any:
        """Transform the swapi data, store results in S3"""
        return Transform(config, extract_result).run()

    @task
    def validate(transform_result: Any) -> Any:
        """QA the swapi Transformation, validate the data, return the transformed data"""
        return Validate(config, transform_result).run()

    @task
    def load(transformed_result: Any) -> bool:
        """Load the Transformed swapi data to the destination"""
        status = Load(config, transformed_result).run()
        return status

    # set up the task dependencies
    load(validate(transform(extract(check()))))


# instantiate the DAG
swapi_dag()
logging.info("swapi DAG instantiated")
