# Archetype ETL. Generated by mkdag 2025-02-02T20:16:59.582422
# A star wars API DAG

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.datasets import Dataset


# load the config
config = json.loads(Variable.get("trigger", default_var='{}'))  # fmt: off


# Define the Dataset
update_datasets = [Dataset(_) for _ in ["foo", "bar"]]
# scheduled_datasets = [
#     Dataset(_) for _ in config["dag"]["extra"].get("scheduled_datasets", [])
# ]


@dag(
    dag_id="upstream-trigger",
    default_args={"retries": 3, "retry_delay": 5},
    description="A trigger DAG",
    start_date=parse("2025-01-01"),
    catchup=False,
    schedule_interval="@daily",
)
def trigger_dag():
    """A trigger wars API DAG"""

    @task(outlets=update_datasets)
    def validate() -> Any:
        """"""
        return True

    validate()

# instantiate the DAG
trigger_dag()
logging.info("trigger DAG instantiated")
