# Archetype ETL. Generated by mkdag 2025-02-02T09:01:02.900565
# Game of Thrones

import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.models.baseoperator import chain


from hooks.got_hook import Check, Extract, Transform, Validate, Load


@dag(
    catchup=False,
    dag_id="got",
    default_args={"retries": 3, "retry_delay": 5},
    description="Game of Thrones",
    schedule_interval="@daily",
    start_date=parse("2025-01-01"),
)
def got_dag():
    """Game of Thrones"""
    config = json.loads(Variable.get("got", default_var=None))  # fmt: off

    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check() -> Any:
        """Check got endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task
    def extract(check_result: Any) -> Any:
        """Extract the got data to S3"""
        return Extract(config, check_result).run()

    @task
    def transform(extract_result: Any) -> Any:
        """Transform the got data, store results in S3"""
        return Transform(config, extract_result).run()

    @task
    def validate(transform_result: Any) -> Any:
        """QA the got Transformation, validate the data, return the transformed data"""
        return Validate(config, transform_result).run()

    @task
    def load(transformed_result: Any) -> bool:
        """Load the Transformed got data to the destination"""
        status = Load(config, transformed_result).run()
        return status

    # set up the task dependencies
    load(validate(transform(extract(check()))))


# instantiate the DAG
got_dag()
logging.info("got DAG instantiated")
