import json
import logging
from abc import abstractmethod
from copy import deepcopy
from datetime import datetime
from dateutil.parser import parse


def is_date(string):
    """Check if a string is a valid date"""
    try:
        parse(string)
        return True
    except ValueError:
        return False


class ETLGenerator:
    """Base class for ETL Archetype Generators"""
    config: dict

    def __init__(self, config: dict):
        """
        Initialize the ETLArchetypeGenerator with a configuration dictionary.

        :param config: Dictionary containing the ETL Archetype configuration.
        """
        assert 'dag' in config, 'dag not found in config file'
        assert 'id' in config['dag'], 'dag_id not found in config file'
        assert 'dag' not in config['dag']['id'], 'by convention, the string "dag" should not be in dag.id, make it simple, short name all lowercase'
        assert 'description' in config['dag'], 'description not found in config file'
        if 'extra' not in config['dag']:
            config['dag']['extra'] = {'configuration': {}}
            logging.warning('extra not found in config file, using empty dict')
        assert 'configuration' in config['dag']['extra'], 'configuration not found in config file'
        self.config = config
        # common attributes
        self.id = config['dag']['id']
        # make the id title case for class names
        self.id_title = self.id.title().replace('_', '')

        # self.output_dataset = None
        # if 'output_dataset' in config['dag']:
        #     self.output_dataset = config['dag']['output_dataset']
        # elif all(['bucket_name' in self.config['extra'], 's3_prefix' in self.config['extra']]):
        #     self.output_dataset = f"s3://{self.config['bucket_name']}/{self.config['s3_prefix']}"

        self.description = config['dag']['description']
        self.generation_comment = f"Archetype ETL. Generated by mkdag {datetime.now().isoformat()}"

    @staticmethod
    def arguments(d: dict) -> list:
        """Render the arguments for the DAG decorator"""
        arguments = []
        for k, v in d.items():
            if k in ['extra', 'tasks'] or k.startswith('_'):
                continue
            if isinstance(v, str):
                if is_date(v):
                    arguments.append(f'{k}=parse("{v}")')
                else:
                    arguments.append(f'{k}="{v}"')
            elif isinstance(v, bool):
                arguments.append(f"{k}={v}")
            elif isinstance(v, int):
                arguments.append(f"{k}={v}")
            elif isinstance(v, dict):
                arguments.append(f"{k}={json.dumps(v, separators=(', ', ': '))}")
            else:
                raise ValueError(f"Unsupported type in dag: {k}={type(v)}")
        return arguments

    @abstractmethod
    def render(self):
        """
        Render the artifact

        :return: A string containing the generated DAG code.
        """
        pass


class DAGGenerator(ETLGenerator):
    """Class for generating DAGs from a configuration dictionary."""
    def render(self):
        """
        Render the DAG as a Python code string.

        :return: A string containing the generated DAG code.
        """
        return f"""# {self.generation_comment}\n# {self.description}
{self.imports()}

{self.dataset()}


{self.dag_decorator()}
{self.dag_body()}
{self.tasks()}


# instantiate the DAG
{self.id}_dag()
logging.info("{self.id} DAG instantiated")
"""

    def dataset(self):
        """
        Render the Dataset class for the DAG.

        :return: A string containing the Dataset class.
        """
        return f'''
# load the config
config = json.loads(
    Variable.get("{self.id}", default_var=None)
)  # fmt: off


# Define the Dataset
dataset = Dataset("{self.id}")
scheduled_datasets = [
    Dataset(_) for _ in config["dag"]["extra"].get("scheduled_datasets", [])
]

'''.strip()

    def dag_decorator(self):
        """
        Render the DAG decorator with the provided configuration.

        :param config: Dictionary containing the DAG configuration.
        :return: A string containing the DAG decorator.
        """
        _config = deepcopy(self.config['dag'])
        _config['dag_id'] = _config.pop('id')
        arguments = self.arguments(_config)
        if 'extra' in _config and 'scheduled_datasets' in _config['extra']:
            arguments.append('schedule=scheduled_datasets')
        # sort the arguments for consistency, format for readability (black)
        arguments = '\n    ' + ',\n    '.join(sorted(arguments))
        return f"@dag({arguments},\n)"

    def dag_body(self):
        """
        Render the body of the DAG function with the provided configuration.

        :param config: Dictionary containing the DAG configuration.
        :return: A string containing the DAG function body.
        """

        return f'''
def {self.id}_dag():
    """{self.description}"""
'''.strip()

    def tasks(self):
        """
        Render the tasks in the DAG.

        :return: A string containing the tasks.
        """
        outlets = 'outlets=[dataset]'

        return f'''
    # Define the tasks
    # TODO - parameterize sensor
    @task.sensor(poke_interval=60, timeout=120, mode="poke", soft_fail=True)
    def check() -> Any:
        """Check {self.id} endpoint, trigger the workflow
        (TODO - parameterize) Wait 60 seconds between pokes, and timeout after 120 seconds.
        """
        condition_met = Check(config).run()
        return condition_met

    @task
    def extract(check_result: Any) -> Any:
        """Extract the {self.id} data to S3"""
        return Extract(config, check_result).run()

    @task
    def transform(extract_result: Any) -> Any:
        """Transform the {self.id} data, store results in S3"""
        return Transform(config, extract_result).run()

    @task({outlets})
    def validate(transform_result: Any) -> Any:
        """QA the {self.id} Transformation, validate the data, return the transformed data. Update output `dataset`"""
        return Validate(config, transform_result).run()

    @task
    def load(transformed_result: Any) -> bool:
        """Load the Transformed {self.id} data to the destination"""
        status = Load(config, transformed_result).run()
        return status

    # set up the task dependencies
    load(validate(transform(extract(check()))))
'''.rstrip()

    def imports(self):
        """
        Render the import statements required for the DAG.

        :param config: Dictionary containing the DAG configuration.
        :return: A string containing the import statements.
        """
        return f"""
import logging
import json
from typing import Any
from dateutil.parser import parse
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.datasets import Dataset

from hooks.{self.id}_hook import Check, Extract, Transform, Validate, Load
"""


class HookGenerator(ETLGenerator):
    """Class for generating Hook from a configuration dictionary."""
    def render(self):
        """
        Render the Hook as a Python code string.

        :return: A string containing the generated DAG code.
        """
        return f"""# {self.generation_comment}\n# {self.description}
{self.imports()}
{self.hook_config()}
{self.hooks()}
"""

    def imports(self):
        return f"""# import statements for {self.id} hook
import json
import logging
from typing import Any

from hooks.base_hook import BaseETLConfig
from hooks.base_hook import BaseETLHook

"""

    def hook_config(self):

        return f'''# class statements for {self.id} hook
class Config(BaseETLConfig):
    """Configuration for the {self.id} API, uses Pydantic for validation"""

    # add any additional configuration parameters here

'''

    def hooks(self):
        return f'''# class statements for {self.id} hook
class {self.id_title}Hook(BaseETLHook):
    """Hook for {self.description}. Base class for ETL hooks."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # add any additional setup here


class Check({self.id_title}Hook):
    """Check {self.id} endpoint, trigger the workflow"""

    def run(self) -> Any:
        # add any additional logic here
        return False


class Extract({self.id_title}Hook):
    """Extract the {self.id} data to S3"""

    def run(self) -> Any:
        # add any additional logic here
        return False


class Transform({self.id_title}Hook):
    """Transform the {self.id} data, store results in S3"""

    def run(self) -> Any:
        # add any additional logic here
        return False


class Validate({self.id_title}Hook):
    """QA the {self.id} Transformation, validate the data, return the transformed data"""

    def run(self) -> Any:
        # add any additional logic here
        return super().validate()


class Load({self.id_title}Hook):
    """Load the Transformed {self.id} data to the destination"""

    def run(self) -> Any:
        # add any additional logic here
        return False                                        
'''.rstrip()


class ConfigGenerator(ETLGenerator):
    """Class for generating Config from a configuration dictionary."""
    def render(self):
        """
        Render the Config as json.

        :return: A string containing the generated DAG code.
        """
        return json.dumps({self.id: self.config['dag']['extra']['configuration']}, separators=(', ', ': '))