# Description: This file contains the Pydantic models for the ETL DSL schema.
from __future__ import annotations

import pathlib
from enum import Enum
from typing import Any, Dict, List, Optional, Union

import tes
from pydantic import BaseModel, Field, RootModel, ConfigDict, model_validator, constr


class EtlDslSchema(BaseModel):
    """Base class for the ETL DSL schema."""

    pass


class CommandDetailed(BaseModel):
    """Detailed command model.

    Attributes:
        operator_type (str): The type of operator to be used.
        command (str): The command to be executed.
    """

    operator_type: str = Field(
        ...,
        description="The type of operator to be used. See https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/index.html for more information.",
    )
    command: str = Field(..., description="The command to be executed.")
    image: Optional[str] = Field(
        None, description="The image to be used for the command."
    )


# Define the class as a union of the two types, a string that will be expanded, or the details
Command = RootModel[Union[str, CommandDetailed]]


# simplify: just use string w/ pattern for now
# class Type(Enum):
#     """Enum for storage object types."""
#     FILE = 'FILE'
#     DIRECTORY = 'DIRECTORY'


class StorageObjectDetailed(BaseModel):
    """Detailed storage object model.

    Attributes:
        url (Optional[str]): The URL of the storage object.
        path (str): The path of the storage object.
        type (Optional[Type]): The type of the storage object.
        name (Optional[str]): The name of the storage object.
        description (Optional[str]): The description of the storage object.
    """

    url: Optional[str] = Field(None, description="The URL of the storage object.")
    path: str = Field(..., description="The path of the storage object.")

    type: Optional[str] = Field(
        "FILE",
        pattern="^(FILE|DIRECTORY)$",
        description="The type of the storage object.",
    )

    name: Optional[str] = Field(None, description="The name of the storage object.")
    description: Optional[str] = Field(
        None, description="The description of the storage object."
    )

    def to_tes_input(self) -> tes.Input:
        """Convert the StorageObject model to a tes.Input object."""
        return tes.Input(
            url=self.url,
            path=self.path,
            type=self.type,
            name=self.name,
            description=self.description,
        )

    def to_tes_output(self) -> tes.Output:
        """Convert the StorageObject model to a tes.Input object."""
        return tes.Output(
            url=self.url,
            path=self.path,
            type=self.type,
            name=self.name,
            description=self.description,
        )


# # Define the class as a union of the two types, a string that will be expanded, or the details
# StorageObject = RootModel[Union[str, StorageObjectDetailed]]


class Dataset(BaseModel):
    """Dataset model.

    Attributes:
        uri (str): The URI of the dataset.
        extra (Optional[Dict[str, Any]]): Additional metadata for the dataset.
    """

    uri: str = Field(..., description="The URI of the dataset.")
    extra: Optional[Dict[str, Any]] = Field(
        None, description="Additional metadata for the dataset."
    )


class Task(BaseModel):
    """Task model.

    Attributes:
        id (str): A unique identifier for the task.
        name (str): The human-readable name of the task.
        description (Optional[str]): A markdown description of the task.
        command (Command): The command to be executed by the task.
        inlets (Optional[List[Dataset]]): A list of Datasets that will trigger the task.
        outlets (Optional[List[Dataset]]): A list of output datasets generated by the task.
    """

    id: str = Field(..., description="A unique identifier for the task.")
    name: str = Field(..., description="The human readable name of the task.")
    description: Optional[str] = Field(
        None, description="A markdown description of the task."
    )
    command: str | CommandDetailed = Field(
        ..., description="The command to be executed by the task."
    )
    inlets: Optional[List[Dataset]] = Field(
        None,
        description="A list of Datasets that will trigger the task. See https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html#what-is-a-dataset",
    )
    outlets: Optional[List[Dataset]] = Field(
        None,
        description="A list of output datasets generated by the task that may trigger downstream tasks. See https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/datasets.html#what-is-a-dataset",
    )
    inputs: Optional[List[str | StorageObjectDetailed]] = Field(
        None,
        description="A list of input storage objects for the command",
    )
    outputs: Optional[List[str | StorageObjectDetailed]] = Field(
        None,
        description="A list of input storage objects from the command",
    )
    callbacks: Optional[dict[str, str]] = Field(
        None,
        description="Map of callbacks for task key=[pre_execute,on_failure, on_success] value=python.callable(context)",
    )

    def to_tes(self) -> tes.Task:
        """Convert the Task model to a tes.Task object."""
        assert isinstance(
            self.command, CommandDetailed
        ), "Command must be detailed, see apply_defaults()"

        # TODO - make this more robust
        image = self.command.image or "ubuntu:latest"

        inputs = []
        if self.inputs:
            for _ in self.inputs:
                assert isinstance(
                    _, StorageObjectDetailed
                ), "expected StorageObjectDetailed, see apply_defaults()"
                inputs.append(_.to_tes_input())
        outputs = []
        if self.outputs:
            for _ in self.outputs:
                assert isinstance(
                    _, StorageObjectDetailed
                ), "expected StorageObjectDetailed, see apply_defaults()"
                outputs.append(_.to_tes_output())

        return tes.Task(
            id=self.id,
            name=self.name,
            description=self.description,
            executors=[tes.Executor(command=self.command.command, image=image)],
            inputs=inputs,
            outputs=outputs,
        )


class ETLSource(BaseModel):
    """ETL source model.

    Attributes:
        id (str): A unique identifier for the data source.
        extractor (Optional[Task]): A list of commands to extract data from the source.
        transformer (Optional[Task]): A list of commands to transform the extracted data.
        loader (Optional[Task]): A list of commands to load the transformed data.
    """

    id: str = Field(..., description="A unique identifier for the data source.")
    extractor: Optional[Task] = Field(
        None, description="A list of commands to extract data from the source."
    )
    transformer: Optional[Task] = Field(
        None, description="A list of commands to transform the extracted data."
    )
    loader: Optional[Task] = Field(
        None, description="A list of commands to load the transformed data."
    )


class BucketScheme(Enum):
    """Enum for bucket schemes."""

    s3 = "s3"
    gs = "gs"
    abfs = "abfs"


class OperatorType(Enum):
    """Enum for operator types."""

    PythonOperator = "PythonOperator"
    BashOperator = "BashOperator"
    TESOperator = "TESOperator"


class ETLProjectDefaults(BaseModel):
    """ETL project defaults model.

    Attributes:
        bucket (str): The name of the bucket where data will be stored.
        bucket_prefix (Optional[str]): A prefix to be used for all data stored in the bucket.
        bucket_scheme (Optional[BucketScheme]): The scheme used for accessing the bucket.
        operator_type (Optional[OperatorType]): The default operator type to be used for executing commands.
    """

    model_config = ConfigDict(use_enum_values=True)
    bucket: str = Field(
        ..., description="The name of the bucket where data will be stored."
    )
    bucket_prefix: Optional[str] = Field(
        None, description="A prefix to be used for all data stored in the bucket."
    )
    bucket_scheme: Optional[BucketScheme] = Field(
        BucketScheme.s3,
        description="The scheme used for accessing the bucket (e.g., s3).",
    )
    operator_type: Optional[OperatorType] = Field(
        OperatorType.BashOperator,
        description="The default operator type to be used for executing commands.",
    )
    callbacks: Optional[dict[str, str]] = Field(
        None,
        description="Map of callbacks for task key=[pre_execute,on_failure, on_success] value=python.callable(context)",
    )
    extractor: Optional[Task] = Field(None, description="The default extractor task.")
    transformer: Optional[Task] = Field(
        None, description="The default transformer task."
    )
    loader: Optional[Task] = Field(None, description="The default transformer task.")


class ETLProject(BaseModel):
    """ETL project model.

    Attributes:
        id (str): A unique identifier for the ETL project.
        name (Optional[str]): The human-readable name of the ETL project.
        description (Optional[str]): A markdown description of the ETL project.
        defaults (ETLProjectDefaults): Default values to be used for each source in the ETL project.
        sources (List[ETLSource]): A list of data sources for the ETL project.
        loader (Optional[Task]): Commands to load the transformed data into the target system.
    """

    id: str = Field(..., description="A unique identifier for the ETL project.")
    name: Optional[str] = Field(
        None, description="The human readable name of the ETL project."
    )
    description: Optional[str] = Field(
        None, description="A markdown description of the ETL project."
    )
    defaults: ETLProjectDefaults = Field(
        ..., description="Default values to be used for each source in the ETL project."
    )
    sources: List[ETLSource] = Field(
        ..., description="A list of data sources for the ETL project."
    )
    loader: Optional[Task] = Field(
        None,
        description="Task to load ALL the transformed data into the target system.",
    )

    model_config = ConfigDict(use_enum_values=True)

    @model_validator(mode="after")
    def ensure_defaults(self) -> "ETLProject":
        """Ensure that all commands,sources,etc are detailed."""
        self.apply_defaults()
        return self

    def apply_defaults(self):
        """Apply default values to all sources."""

        # helper
        def ensure_storage_objects(
            storage_objects: Optional[list[str | StorageObjectDetailed]],
            defaults: ETLProjectDefaults,
        ) -> Optional[list[str | StorageObjectDetailed]]:
            """Expand storage objects to include default values."""
            if not storage_objects:
                return storage_objects
            _storage_objects: list[str | StorageObjectDetailed] = []
            for storage_object in storage_objects:
                if isinstance(storage_object, StorageObjectDetailed):
                    _storage_objects.append(storage_object)
                    continue
                storage_object = StorageObjectDetailed(
                    path=storage_object,
                    url=None,
                    type="FILE",
                    name=None,
                    description=None,
                )
                if storage_object.url is None:
                    storage_object.url = f"{defaults.bucket_scheme}://{defaults.bucket}/{defaults.bucket_prefix}/{storage_object.path}"
                # simple parsing
                parsed = pathlib.Path(storage_object.path)
                storage_object.type = "FILE"
                # no suffix, must be a directory
                if not parsed.suffix:
                    storage_object.type = "DIRECTORY"
                storage_object.name = parsed.name
                storage_object.description = f"Generated from {storage_object.path}"

                _storage_objects.append(storage_object)

            return _storage_objects

        # helper
        def ensure_task(
            task: Optional[Task], defaults: ETLProjectDefaults
        ) -> Optional[Task]:
            """Expand task to include default values."""
            if task is None:
                return None

            if isinstance(task.command, str):
                task.command = CommandDetailed(
                    command=task.command,
                    operator_type=str(defaults.operator_type),
                    image=None,
                )

            task.inputs = ensure_storage_objects(task.inputs, defaults)
            task.outputs = ensure_storage_objects(task.outputs, defaults)

            if not task.callbacks and defaults.callbacks:
                task.callbacks = defaults.callbacks

            return task

        # process etl project
        for source in self.sources:
            if not source.extractor and self.defaults.extractor:
                source.extractor = self.defaults.extractor.model_copy(deep=True)
            source.extractor = ensure_task(source.extractor, self.defaults)

            if not source.transformer and self.defaults.transformer:
                source.transformer = self.defaults.transformer.model_copy(deep=True)
            source.transformer = ensure_task(source.transformer, self.defaults)

            if not source.loader and self.defaults.loader:
                source.loader = self.defaults.loader.model_copy(deep=True)
            source.loader = ensure_task(source.loader, self.defaults)

            # apply dataset defaults
            if source.extractor:
                source.extractor.inlets = source.extractor.inlets or None
                source.extractor.outlets = source.extractor.outlets or [
                    Dataset(uri=f"{source.id}-raw")
                ]
            if source.transformer:
                source.transformer.inlets = source.transformer.inlets or [
                    Dataset(uri=f"{source.id}-raw")
                ]
                source.transformer.outlets = source.transformer.outlets or [
                    Dataset(uri=f"{source.id}-processed")
                ]
            if source.loader:
                source.loader.inlets = source.loader.inlets or [
                    Dataset(uri=f"{source.id}-processed")
                ]
                source.loader.outlets = source.loader.outlets or [
                    Dataset(uri=f"{source.id}-loaded")
                ]

        self.loader = ensure_task(self.loader, self.defaults)
        if self.loader:
            load_task_inlets = []
            for source in self.sources:
                if source.transformer:
                    load_task_inlets.extend(source.transformer.outlets)

            self.loader.inlets = load_task_inlets
            self.loader.outlets = self.loader.outlets or [
                Dataset(uri=f"{self.id}-loaded")
            ]
