# Archetype ETL. Generated by mkdag 2025-02-02T10:40:12.310664
# A star wars API DAG
# import statements for swapi hook
import json
import logging
from typing import Any

from hooks.base_hook import BaseETLConfig
from hooks.base_hook import BaseETLHook

from sensors.change_sensors import check_etag
from json2html import *


# class statements for swapi hook
class Config(BaseETLConfig):
    """Configuration for the swapi API, uses Pydantic for validation"""

    # add any additional configuration parameters here


# class statements for swapi hook
class SwapiHook(BaseETLHook):
    """Hook for A star wars API DAG. Base class for ETL hooks."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # add any additional setup here


class Check(SwapiHook):
    """Check swapi endpoint, trigger the workflow"""

    def run(self) -> Any:
        """ Check if the ETag of the Star Wars API has changed """
        return check_etag(url=self.config.inputs['catalog'], variable_name=self.config.sensor_variable_name)


class Extract(SwapiHook):
    """Extract the swapi data to S3"""

    def run(self) -> Any:
        """ Download the Star Wars API catalog and resources to S3 """
        response = self.download_to_s3(self.config.inputs['catalog'], "swapi.json")
        root = response.json()
        for resource_name, url in root.items():
            self.download_to_s3(url=url, file_name=f"{resource_name}.json")
        return True


class Transform(SwapiHook):
    """Transform the swapi data, store results in S3"""

    def run(self) -> Any:
        """ Transform the Star Wars API resources from JSON to HTML """
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [key for key in keys if key.endswith(".json")]
        assert keys, f"No json files found in s3://{self.config.bucket_name}/{self.config.s3_prefix}"
        for key in keys:
            resource = json.loads(self.s3_hook.read_key(key=key, bucket_name=self.config.bucket_name))
            # Transform the resource
            html = json2html.convert(json=resource)
            # Save the transformed resource
            self.s3_hook.load_string(
                html,
                key=key.replace(".json", ".html"),
                bucket_name=self.config.bucket_name,
                replace=True
            )
            logging.info(f"Transformed {key} to {key.replace('.json', '.html')}")
        return True


class Validate(SwapiHook):
    """QA the swapi Transformation, validate the data, return the transformed data"""

    def run(self) -> Any:
        """Validate the transformed data"""
        rc = super().validate()
        logging.info(f"Base validation result: {rc}")
        if not rc:
            return rc
        # add any additional validation logic here
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [key for key in keys if key.endswith(".html")]
        assert keys, f"No html files found in s3://{self.config.bucket_name}/{self.config.s3_prefix}"

        return True


class Load(SwapiHook):
    """Load the Transformed swapi data to the destination"""

    def run(self) -> Any:
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [key for key in keys if key.endswith(".html")]
        for key in keys:
            logging.info(f"(mock) Loading {key} into the webserver")
        return True
