# Archetype ETL. Generated by mkdag 2025-02-02T09:01:03.053343
# Game of Thrones
# import statements for got hook
import json
import logging
from typing import Any

from hooks.base_hook import BaseETLConfig
from hooks.base_hook import BaseETLHook

from json2html import *
from sensors.change_sensors import last_modified


# class statements for got hook
class Config(BaseETLConfig):
    """Configuration for the got API, uses Pydantic for validation"""

    # add any additional configuration parameters here


# class statements for got hook
class GotHook(BaseETLHook):
    """Hook for Game of Thrones. Base class for ETL hooks."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # add any additional setup here


class Check(GotHook):
    """Check got endpoint, trigger the workflow"""

    def run(self) -> Any:
        """GOT API does not support ETag, use last-modified"""
        first_url = next(iter(self.config.inputs.values()))
        return last_modified(url=first_url, variable_name=self.config.sensor_variable_name, header_name="last-modified")


class Extract(GotHook):
    """Extract the got data to S3"""

    def run(self) -> Any:
        """Extract all the data from the GOT API"""
        for name, url in self.config.inputs.items():
            self.download_to_s3(url, f"{name}.json")
        return True


class Transform(GotHook):
    """Transform the got data, store results in S3"""

    def run(self) -> Any:
        """ Transform the GOT resources from JSON to HTML """
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [key for key in keys if key.endswith(".json")]
        assert keys, f"No json files found in s3://{self.config.bucket_name}/{self.config.s3_prefix}"
        for key in keys:
            resource = json.loads(self.s3_hook.read_key(key=key, bucket_name=self.config.bucket_name))
            # Transform the resource
            html = json2html.convert(json=resource)
            # Save the transformed resource
            self.s3_hook.load_string(
                html,
                key=key.replace(".json", ".html"),
                bucket_name=self.config.bucket_name,
                replace=True
            )
            logging.info(f"Transformed {key} to {key.replace('.json', '.html')}")
        return True


class Validate(GotHook):
    """QA the got Transformation, validate the data, return the transformed data"""

    def run(self) -> Any:
        # add any additional logic here
        return super().validate()


class Load(GotHook):
    """Load the Transformed got data to the destination"""

    def run(self) -> Any:
        # add any additional logic here
        return True
