# Archetype ETL. Generated by mkdag 2025-02-02T10:40:12.310664
# A star wars API DAG
# import statements for swapi hook
import json
import logging
from abc import ABC
from typing import Any
from urllib.parse import urlparse

from hooks.base_hook2 import BaseETLConfig
from hooks.base_hook2 import BaseETLHook

from sensors.change_sensors import check_etag
from json2html import *


# class statements for swapi hook
class Config(BaseETLConfig):
    """Configuration for the swapi API, uses Pydantic for validation"""

    # add any additional configuration parameters here


# class statements for swapi hook
class Swapi2Hook(BaseETLHook, ABC):
    """Hook for A star wars API DAG. Base class for ETL hooks."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # add any additional setup here


class Check(Swapi2Hook):
    """Check swapi endpoint, trigger the workflow"""

    def run(self, *args, **kwargs) -> Any:
        """ Check if the ETag of the Star Wars API has changed """
        logging.info(f"Checking variable_name {self.config.inputs['catalog']}")
        return check_etag(url="https://swapi.dev/api/", variable_name=self.config.sensor_variable_name)


class Extract(Swapi2Hook):
    """Extract the swapi data to S3"""

    def run(self, *args, **kwargs) -> Any:
        """ Download the Star Wars API catalog and resources to S3 """
        http_conn_id, relative_url = self.parse_http_hook_url(self.config.inputs['catalog'])

        response, bucket_url = self.download_to_s3(http_conn_id=http_conn_id, url=relative_url, file_name="swapi.json")
        root = response.json()
        bucket_urls = [bucket_url]
        for resource_name, url in root.items():
            relative_url = urlparse(url).path
            response, bucket_url = self.download_to_s3(http_conn_id, url=relative_url, file_name=f"{resource_name}.json")
            bucket_urls.append(bucket_url)
        return bucket_urls


class Transform(Swapi2Hook):
    """Transform the swapi data, store results in S3"""

    def run(self, *args, **kwargs) -> Any:
        """ Transform the Star Wars API resources from JSON to HTML """
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [key for key in keys if key.endswith(".json")]
        assert keys, f"No json files found in s3://{self.config.bucket_name}/{self.config.s3_prefix}"
        bucket_urls = []
        for key in keys:
            resource = json.loads(self.s3_hook.read_key(key=key, bucket_name=self.config.bucket_name))
            # Transform the resource
            html = json2html.convert(json=resource)
            # Save the transformed resource
            s3_key = key.replace(".json", ".html")
            self.s3_hook.load_string(
                html,
                key=s3_key,
                bucket_name=self.config.bucket_name,
                replace=True
            )
            bucket_url = f"s3://{self.config.bucket_name}/{s3_key}"
            bucket_urls.append(bucket_url)
            logging.info(f"Transformed {key} to {bucket_url}")
        return bucket_urls


class Validate(Swapi2Hook):
    """QA the swapi Transformation, validate the data, return the transformed data"""

    def run(self, *args, **kwargs) -> Any:
        """Validate the transformed data"""
        rc = super().validate()
        logging.info(f"Base validation result: {rc}")
        if not rc:
            return rc
        # add any additional validation logic here
        keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        keys = [f"s3://{self.config.bucket_name}/{key}" for key in keys if key.endswith(".html")]
        assert keys, f"No html files found in s3://{self.config.bucket_name}/{self.config.s3_prefix}"

        return keys


class Load(Swapi2Hook):
    """Load the Transformed swapi data to the destination"""

    def run(self, manifest) -> Any:
        """Load the Transformed swapi data to the destination"""
        logging.info(f"Loading {manifest}")

        # keys = self.s3_hook.list_keys(bucket_name=self.config.bucket_name, prefix=self.config.s3_prefix)
        # keys = [key for key in keys if key.endswith(".html")]
        # for key in keys:
        #     logging.info(f"(mock) Loading {key} into the webserver")

        for url in manifest:
            parsed = urlparse(url)
            key = parsed.path
            logging.info(f"(mock) Loading {key} into the webserver from {self.s3_hook, self.config.bucket_name}")

        return True
